<script>
    import PageLayout from '../../components/pageLayout.svelte'
</script>

<PageLayout>
    <span slot="title">Areo Browser</span>
    <div slot="content">

        <a href="https://areobrowser.com" target="_blank" rel="noopener noreferrer">
            <img class="rounded-md object-cover" src="./testImage.jpg" alt="Areo Browser" />
        </a>

        <h2 class="mt-6 text-xl text-pink-600 font-light">Links</h2>
        <a href="https://areobrowser.com" target="_blank" rel="noopener noreferrer">areobrowser.com</a>

        <h2 class="mt-6 text-xl text-pink-600 font-light">What is it?</h2>
        <p class="mt-2">
            AreoBrowser allows you to easily search and explore all available HiRISE DTMs (Digital Terrain Models) in full 3D.
            Populated with models generated by Areo, you can alter level of detail, view the models in red/blue anaglyph,
            and even download the models directly for use in other 3D applications. AreoBrowser is the second in a line of
            one-month long projects. Find out more in the video below :
        </p>

        <h2 class="mt-6 text-xl text-pink-600 font-light">Features</h2>
		<!-- https://tailwindgrids.com/#/ -->
		<div class="flex flex-wrap -mx-2 overflow-hidden sm:-mx-4">
            <div class="my-2 mb-4 px-2 w-full overflow-hidden sm:my-4 sm:px-4 sm:w-full md:w-1/2 xl:w-1/3">               
            </div>
        </div>
        
        <h2 class="mt-6 text-xl text-pink-600 font-light">Related Posts</h2>
	</div>
</PageLayout>