import { readable } from 'svelte/store';

const projects = readable([
    {
        id: 1,
        slug:"areo-browser",
        name:"Areo Browser", 
        smallImage: "./testImage.jpg",
        largeImage : "./testImage.jpg",
        shortDesc:"Explore nearly 2000 3D models of Mars, using data from HiRISE & HRSC.",
        links:["https://areobrowser.com"],
        desc:"AreoBrowser allows you to easily search and explore all available HiRISE DTMs (Digital Terrain Models) in full 3D. Populated with models generated by Areo, you can alter level of detail, view the models in red/blue anaglyph, and even download the models directly for use in other 3D applications.",
        features: [
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"}
        ],
        todos:[
            "Model downloads at any resolution",
            "3D-printable model downloads at any resolution",
            "Ability to save an image of the current view, with a transparent background",
            "Ability to share a link to the current model + camera angle",
            "Realistic Martian lighting based upon location + a given time "
        ],
        tagName: "areobrowser"
    },
    {
        id: 2, 
        slug:"juno-observer",
        name:"Juno Observer", 
        smallImage: "./testImage.jpg",
        largeImage : "./testImage.jpg",
        shortDesc:"Explore imagery from NASA's Juno spacecraft, projected onto a 3D Jupiter.",
        links:["https://juno.observer"],
        desc:"Juno Observer something something something something.",
        features: [
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"},
            {title:"Feature", desc:"Description of feature", image:"./testImage.jpg"}
        ],
        todos:[
            "Full re-write"
        ],
        tagName: "junoobserver"
    }
]);

export { projects }